# Generated by Django 4.2.7 on 2023-11-12 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=200),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Computers", "Computers"),
                            ("Kids", "Kids"),
                            ("Food", "Food"),
                            ("Home", "Home"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=2),
                ),
                ("stock", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
